#!gmake 

#-----------------------------------------
#Basic Stuff -----------------------------
CC          = g++ 
cc          = gcc

#-----------------------------------------
#Optimization ----------------------------
OPT   = -fast

#-----------------------------------------
# X       --------------------------------
FRAMEWORK = -framework GLUT
FRAMEWORK += -framework OpenGL
MAC_INC  =   -L"/System/Library/Frameworks/OpenGL.framework/Libraries"
MAC_LIB  =   -lGL -lGLU -lm -lstdc++

#-----------------------------------------
#-----------------------------------------

TARGETS = main

OBJECTS = main.o

#-----------------------------------------


CCOPTS = $(OPT) $(MAC_INC) -DOSX
LDOPTS = $(OPT) $(MAC_INC) $(MAC_LIB) -DOSX

#-----------------------------------------
#-----------------------------------------

default: $(TARGETS)

clean:
	/bin/rm -f *.o $(TARGETS)

#-----------------------------------------
#-----------------------------------------

main: main.o grid.o
	$(CC) main.o grid.o $(FRAMEWORK) $(LDOPTS) -o main

grid.o: grid.cpp
	$(CC) grid.cpp -c $(CCOPTS)
	
main.o: main.cpp
	$(CC) main.cpp -c $(CCOPTS)


#export LD_LIBRARY_PATH="/usr/sww/pkg/Mesa/lib:/usr/lib:/usr/sww/lib"

